name: spdx
description: Verify that files include SPDX license headers

branding:
  icon: zap
  color: gray-dark

inputs:
  licenses:
    description: >
      A newline-separated list of all accepted licenses. For example:

      licenses: |-
        Apache-2.0
        Apache-2.0 WITH LLVM-exception
    required: true
    default: ''
  ignore-paths:
    description: >
      A newline-separated list of any paths to ignore. For example:

      ignore-paths: |-
        src/generated/
        src/ignore-file.md
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.licenses }}" | xargs -d "\n" $GITHUB_ACTION_PATH/verify-spdx-headers
      shell: bash
      env:
        INPUT_IGNORE_PATHS: ${{ inputs.ignore-paths }}
